version: "3.9"
services:
  api:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
              --access-logfile -
              --reload
              "libraryapi.app:create_app()"
    ports:
      - "8000:8000"
    working_dir: /libraryapi
    volumes:
      - "./:/librarypi"
